name: OpenWrt-CI

on:
  schedule:
    - cron: 0 3 * * 3
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    

permissions:
  contents: write

jobs:
  build_openwrt:
    name: Build OpenWrt Firmware
    runs-on: ubuntu-latest
    steps:
      - name: space cleanup and initiallzation environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo -E apt-mark hold grub-efi-amd64-signed

      - name: checkout openwrt source code
        uses: actions/checkout@v3          

      - name: run build script
        run: |
          chmod +x ./build.sh
          bash ./build.sh
          mkdir -p ./artifacts/firmware
          cp -rf $(find ./lede/bin/targets -type f -name "openwrt-*.img.gz") ./artifacts/firmware
          echo "strDate=$(TZ=UTC-8 date +%Y-%m-%d)" >> $GITHUB_ENV

      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: OpenWrt_firmware
          path: ./artifacts/firmware/*.gz

      - name: if_schedule
        if: github.event_name == 'schedule'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.strDate }}
          name: 自动构建 ${{ env.strDate }}
          draft: false
          prerelease: false
          files: ./artifacts/firmware/*.gz
      
      - name: get_tag
        if: github.event_name == 'push'
        id: get_tag
        run: |
          echo "tag=$(echo ${GITHUB_REF#refs/*/})" >> $GITHUB_ENV

      - name: if_push
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ env.tag }}
          draft: false
          prerelease: false
          files: ./artifacts/firmware/*.gz